name: OpenACR output accessibility testing

on:
  pull_request:

jobs:
  build-test:
    name: Building app, generate output examples and test for accessibility issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install dependencies.
        run: npm ci

      - name: Output Drupal HTML.
        run: npx ts-node src/openacr.ts output -f openacr/drupal-9.yaml -c catalog/2.4-edition-wcag-2.1-508-en.yaml -o output/drupal-9.html

      - name: Output Example HTML.
        run: npx ts-node src/openacr.ts output -f tests/examples/valid.yaml -c catalog/2.4-edition-wcag-2.0-508-en.yaml -o output/valid.html

      - name: Run accessibility test against all HTML files.
        run: npm run a11y-test
